# Generated by Django 4.2 on 2023-11-01 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoai_openai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='max_tokens',
        ),
        migrations.AlterField(
            model_name='openaimodel',
            name='model',
            field=models.CharField(default='gpt-3.5-turbo', max_length=100),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='geoai_openai.openaimodel'),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='temperature',
            field=models.FloatField(default=0.3),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='top_p',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='openaimodel',
            name='token',
            field=models.ForeignKey(default=4097, on_delete=django.db.models.deletion.CASCADE, to='geoai_openai.maxtokens'),
        ),
    ]
