# Generated by Django 4.2 on 2023-11-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoai_openai', '0002_maxtokens_remove_parameters_max_tokens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openaimodel',
            name='token',
        ),
        migrations.AddField(
            model_name='parameters',
            name='max_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='MaxTokens',
        ),
    ]
