# Generated by Django 4.2 on 2023-11-01 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoai_openai', '0005_alter_openaimodel_token_delete_maxtokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField(default=4097)),
            ],
        ),
        migrations.AlterField(
            model_name='openaimodel',
            name='token',
            field=models.ForeignKey(default=4097, on_delete=django.db.models.deletion.CASCADE, to='geoai_openai.maxtokens'),
        ),
    ]
