# Generated by Django 4.2 on 2023-11-01 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoai_openai', '0006_maxtokens_alter_openaimodel_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='maxtokens',
            name='token',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='openaimodel',
            name='model',
            field=models.ForeignKey(default='gpt-3.5-turbo', on_delete=django.db.models.deletion.CASCADE, to='geoai_openai.modelname'),
        ),
    ]
