# Generated by Django 4.2 on 2023-11-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoai_openai', '0007_modelname_alter_maxtokens_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='instruction',
            field=models.TextField(default='You are a helpful assistant.'),
        ),
    ]
