# Generated by Django 4.2 on 2023-10-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoai_payments', '0002_alter_payments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_id',
            field=models.CharField(default='', max_length=225),
        ),
    ]
