# Generated by Django 4.2 on 2023-04-10 16:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_remove_subject_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Topic',
        ),
    ]
