# Generated by Django 4.2 on 2023-04-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_subject_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
