# Generated by Django 4.2 on 2023-04-23 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_question_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.answer'),
        ),
    ]
