# Generated by Django 4.2 on 2023-05-02 23:23

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_tag_alter_question_answer_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='avatar',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/avatars'),
        ),
        migrations.AddField(
            model_name='question',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(blank=True, default='0.5x0.5', editable=False, max_length=20, null=True),
        ),
    ]
