# Generated by Django 4.2 on 2023-05-03 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_question_avatar_question_ppoi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ppoi',
        ),
    ]
