# Generated by Django 4.2 on 2023-05-03 00:40

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_question_avatar_remove_question_ppoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='avatar',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/avatars'),
        ),
        migrations.AddField(
            model_name='question',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(blank=True, default='0.5x0.5', editable=False, max_length=20, null=True),
        ),
    ]
