# Generated by Django 4.2 on 2023-05-03 21:21

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_question_avatar_question_ppoi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ppoi',
        ),
        migrations.AddField(
            model_name='topic',
            name='avatar',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/avatars'),
        ),
        migrations.AddField(
            model_name='topic',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(blank=True, default='0.5x0.5', editable=False, max_length=20, null=True),
        ),
    ]
