# Generated by Django 4.2 on 2023-05-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_remove_topic_avatar_remove_topic_ppoi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='ppoi',
        ),
        migrations.AlterField(
            model_name='question',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatars'),
        ),
    ]
