# Generated by Django 4.2 on 2023-05-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_remove_question_ppoi_alter_question_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='translated',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='translated',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
