# Generated by Django 4.2 on 2023-05-31 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_topic_translated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['created_at']},
        ),
    ]
