# Generated by Django 4.2 on 2023-07-06 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_rename_translated_answer_eng_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='object_id',
        ),
        migrations.AddField(
            model_name='topic',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='chat.question'),
            preserve_default=False,
        ),
    ]
