# Generated by Django 4.2 on 2023-07-06 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_alter_topic_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='chat.topic'),
        ),
    ]
