# Generated by Django 4.2 on 2023-09-28 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0027_alter_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('completion_tokens', models.PositiveIntegerField(db_index=True, default=0)),
                ('prompt_tokens', models.PositiveIntegerField(db_index=True, default=0)),
                ('total_tokens', models.PositiveIntegerField(db_index=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='tokens',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='chat.tokens'),
        ),
    ]
