# Generated by Django 4.2 on 2023-09-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_alter_question_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tokens',
        ),
        migrations.DeleteModel(
            name='Tokens',
        ),
    ]
