# Generated by Django 4.2 on 2023-08-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='mode_style',
            field=models.CharField(default='geoai/css/pygments_styles/sas.css', max_length=255),
        ),
    ]
