# Generated by Django 4.2 on 2023-08-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_setting', '0002_usersetting_mode_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='mode_style',
            field=models.CharField(default='/static/geoai/css/pygments_styles/monokai.css', max_length=255),
        ),
    ]
