# Generated by Django 4.2 on 2023-09-28 15:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_setting', '0005_usertokenslimit_delete_usertokens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTokensLimit',
            new_name='UserTokens',
        ),
    ]
