# Generated by Django 4.2 on 2023-10-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_setting', '0007_alter_usertokens_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertokens',
            name='token_id',
            field=models.CharField(default='', max_length=225),
        ),
    ]
