# Generated by Django 4.2 on 2023-10-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_setting', '0008_usertokens_token_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='chat_lang',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='interface_lang',
            field=models.CharField(default='', max_length=3),
        ),
    ]
